name: Build Documentation

on:
  push:
    branches: [ "build-manual" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Build manual
        run: |
          mv builds/hyde hyde # Using the latest version of Hyde, which also lets us run this without Composer which makes it much faster
          mkdir vendor && touch vendor/autoload.php # Autoloader is not needed for production, just for development to get the debug helpers
          php bin/build-manual.php
          rm -rf vendor

      - name: Create site from Readme
        run: |
          mkdir _pages
          mv README.md _pages/index.md
          rm -rf !'_pages'

      - name: Move Hyde config
        run: mv .github/docs/hyde.yml hyde.yml

      - uses: hydephp/action@master

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: _site

      - name: Deploy to GitHub Pages
        id: pages-deployment
        uses: actions/deploy-pages@v1
