name: Build Documentation

on:
  push:
    branches: [ "build-manual" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Create site from Readme
        run: |
          mkdir _pages
          mv README.md _pages/index.md
          touch _pages/manual.html # Make Hyde aware of the manual

      - name: Move Hyde config
        run: mv .github/docs/hyde.yml hyde.yml

      - uses: hydephp/action@master

      - name: Build manual
        run: |
          php bin/build-manual.php
          mv docs/manual _site/manual
          mv _site/manual/manual.html _site/manual/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: _site

      - name: Deploy to GitHub Pages
        id: pages-deployment
        uses: actions/deploy-pages@v1
