name: Build Documentation

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Create site from Readme
        run: |
          mkdir _pages 
          mv README.md _pages/index.md 
          rm -rf !'_pages'
      - uses: hydephp/action@master
        with:
          deploy-to: "pages"
