name: Create a new release

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: The SemVer level of the release
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    name: Prepare a new release

    steps:
      - uses: actions/checkout@v3

      - name: Bump application version
        id: bump-version
        run: |
          php bin/bump-application-version.php ${{ github.event.inputs.type }}
          echo "version=$(php bin/get-release-version.php)" >> $GITHUB_ENV
          echo "Version: ${{ steps.bump-version.outputs.version }}"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "HydeCLI v${{ steps.bump-version.outputs.version }}"
          title: "HydeCLI v${{ steps.bump-version.outputs.version }}"
          branch: "release/v${{ steps.bump-version.outputs.version }}"
          add-paths: 'app/Application.php'
          base: stable
          body: |
            This pull request was automatically created by the [HydeCLI release workflow](.github/workflows/create-release.yml).

            Please review and merge it to publish a new release, which will be created automatically.
          delete-branch: true
          labels: release
