# This workflow will build the application and publish a new release.
# It is triggered by pushes to the protected stable branch used for releases.
# This process is triggered via the GitHub UI using the create-release.yml action.

name: Build and publish a new release

on:
  push:
    branches: [ "stable" ]

permissions:
  contents: read

jobs:

  sync:
    runs-on: ubuntu-latest
    name: Merge stable branch into master

    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ref: master

      - name: Merge stable branch into master
        run: |
          git fetch origin stable:stable
          git merge stable
          git push origin master

  build:
    runs-on: ubuntu-latest
    name: Build standalone executable

    steps:
      - uses: actions/checkout@v3

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --no-suggest --prefer-dist

      - name: Get build version
        id: build-version
        run: |
          echo "version=$(php ./bin/get-release-version.php)" >> $GITHUB_OUTPUT
          echo "Version: v$(php ./bin/get-release-version.php)"
          php ./bin/get-release-version.php > version

      - name: Build executable
        run: php hyde standalone:build --build-version-suffix="${{ steps.build-version.outputs.sha_short }}"

      - name: Verify executable
        run: php builds/hyde

      - name: Verify executable version
        run: php builds/hyde --version

      - name: Calculate checksum
        run: |
          cd builds
          sha256sum hyde > checksum.txt
          echo "SHA256 checksum of the application binary: $(cat checksum.txt)"

      - name: Commit executable
        uses: EndBug/add-and-commit@v9
        with:
          add: builds/hyde
          message: "Build standalone executable"

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: hyde
          path: builds/hyde

      - name: Upload the checksum artifact
        uses: actions/upload-artifact@v3
        with:
          name: checksum
          path: builds/checksum.txt

      - name: Upload the version number artifact
        uses: actions/upload-artifact@v3
        with:
          name: version
          path: version

  release:
    needs: build
    runs-on: ubuntu-latest
    name: Publish release

    permissions:
      contents: write

    steps:
      - name: Download the application artifact
        uses: actions/download-artifact@v3
        with:
          name: hyde
          path: builds

      - name: Download the checksum artifact
        uses: actions/download-artifact@v3
        with:
          name: checksum
          path: builds

      - name: Download the version number artifact
        uses: actions/download-artifact@v3
        with:
          name: version

      - name: Prepare version information
        run:  |
          echo "CHECKSUM=$(cat builds/checksum.txt | cut -d ' ' -f 1)" >> $GITHUB_ENV
          echo "VERSION=$(cat version)" >> $GITHUB_ENV

      - name: Print version information
        run: |
          echo "Version: v${{ env.VERSION }}"
          echo "Checksum: ${{ env.CHECKSUM }}"

      - name: Create a release
        uses: ncipollo/release-action@v1
        with:
          name: v${{ env.VERSION }}
          tag: v${{ env.VERSION }}
          commit: ${{ github.sha }}
          updateOnlyUnreleased: true
          generateReleaseNotes: true
          artifacts: builds/hyde, builds/checksum.txt
