name: Test Suite

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        php: [8.1, 8.2, 8.3]

    runs-on: ${{ matrix.os }}
    name: Run tests - ${{ matrix.os }} ${{ matrix.php }}

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: fileinfo

      - uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --no-suggest --prefer-dist

      - name: Execute tests (Unit and Feature tests) via Pest
        run: vendor/bin/pest
